### PR TITLE
Some fixes related to resource specificaitons

### PR DESCRIPTION
**Pull request by protodeniz**
Hi,

This PR includes changes related to ValueFlows.Knowledge.ResourceSpecification.  If you find anything incorrect, please let me know.

The PR mainly fixes `createResourceSpecification` and `updateResourceSpecification` mutations.
There's probably something broken related to Tags, but I need to further investigate (can really use some comments on that :D).

Thanks,
srfsh

### CODE REVIEW

**Comment by mayel** [comment]
Thanks for the PR!

Actually classifications don't have their own field in the DB because we're using the bonfire_classify and bonfire_tag extensions for classifications. There's indeed some logic missing to turn classifications provided as URLs into categories/tags (because we started by simply using an added `tags` GraphQL field for that instead) so I'd hook that up instead of adding a specific field on each schema that supports classifications.

**Comment by mayel** [comment]
See `ValueFlows.Util.maybe_classification` and `ValueFlows.Util.try_tag_thing`

**Comment by protodeniz** [comment]
I see.  I'll work on that more, later.  Thanks for explaining.  ^^

**Comment by mayel** [comment]
I should add that these functions currently support tags being a ULID of a pointable object, or a URI of an ActivityPub actor. If other urls need to be used (such as a Wikidata link) support for that has yet to be implemented.

**Pull request merged**
